# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{talia_core}
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Danilo Giacomi", "Roberto Tofani", "Luca Guidi", "Daniel Hahn"]
  s.date = %q{2009-10-14}
  s.default_executable = %q{talia}
  s.description = %q{This is the core plugin for building a digital library with Talia/Rails.}
  s.email = %q{ghub@limitedcreativity.org}
  s.executables = ["talia"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "lib/JXslt/jxslt.rb",
     "lib/acts_as_roled.rb",
     "lib/core_ext.rb",
     "lib/core_ext/platform.rb",
     "lib/core_ext/string.rb",
     "lib/custom_template.rb",
     "lib/loader_helper.rb",
     "lib/mysql.rb",
     "lib/progressbar.rb",
     "lib/role.rb",
     "lib/talia_cl.rb",
     "lib/talia_cl/command_line.rb",
     "lib/talia_cl/commands/standalone.rb",
     "lib/talia_cl/commands/standalone/cl_options.rb",
     "lib/talia_cl/commands/standalone/standalone_generate.rb",
     "lib/talia_cl/commands/talia_console.rb",
     "lib/talia_cl/commands/talia_console/cl_options.rb",
     "lib/talia_cl/commands/talia_console/console_commands.rb",
     "lib/talia_cl/commands/talia_console/talia_commands.rb",
     "lib/talia_cl/core_commands.rb",
     "lib/talia_core.rb",
     "lib/talia_core/active_source.rb",
     "lib/talia_core/active_source_parts/class_methods.rb",
     "lib/talia_core/active_source_parts/predicate_handler.rb",
     "lib/talia_core/active_source_parts/rdf.rb",
     "lib/talia_core/active_source_parts/sql_helper.rb",
     "lib/talia_core/active_source_parts/xml/base_builder.rb",
     "lib/talia_core/active_source_parts/xml/generic_reader.rb",
     "lib/talia_core/active_source_parts/xml/rdf_builder.rb",
     "lib/talia_core/active_source_parts/xml/source_builder.rb",
     "lib/talia_core/active_source_parts/xml/source_reader.rb",
     "lib/talia_core/agent.rb",
     "lib/talia_core/background_jobs/job.rb",
     "lib/talia_core/background_jobs/progress_job.rb",
     "lib/talia_core/collection.rb",
     "lib/talia_core/data_types/data_loader.rb",
     "lib/talia_core/data_types/data_record.rb",
     "lib/talia_core/data_types/delayed_copier.rb",
     "lib/talia_core/data_types/file_record.rb",
     "lib/talia_core/data_types/file_store.rb",
     "lib/talia_core/data_types/iip_data.rb",
     "lib/talia_core/data_types/iip_loader.rb",
     "lib/talia_core/data_types/image_data.rb",
     "lib/talia_core/data_types/media_link.rb",
     "lib/talia_core/data_types/mime_mapping.rb",
     "lib/talia_core/data_types/path_helpers.rb",
     "lib/talia_core/data_types/pdf_data.rb",
     "lib/talia_core/data_types/simple_text.rb",
     "lib/talia_core/data_types/temp_file_handling.rb",
     "lib/talia_core/data_types/xml_data.rb",
     "lib/talia_core/dc_resource.rb",
     "lib/talia_core/dummy_handler.rb",
     "lib/talia_core/dummy_source.rb",
     "lib/talia_core/errors.rb",
     "lib/talia_core/initializer.rb",
     "lib/talia_core/ordered_source.rb",
     "lib/talia_core/rails_ext.rb",
     "lib/talia_core/rails_ext/actionpack.rb",
     "lib/talia_core/rails_ext/actionpack/action_controller.rb",
     "lib/talia_core/rails_ext/actionpack/action_controller/record_identifier.rb",
     "lib/talia_core/rdf_import.rb",
     "lib/talia_core/rdf_resource.rb",
     "lib/talia_core/semantic_collection_item.rb",
     "lib/talia_core/semantic_collection_wrapper.rb",
     "lib/talia_core/semantic_property.rb",
     "lib/talia_core/semantic_relation.rb",
     "lib/talia_core/source.rb",
     "lib/talia_core/source_transfer_object.rb",
     "lib/talia_core/workflow.rb",
     "lib/talia_core/workflow/base.rb",
     "lib/talia_core/workflow/publication_workflow.rb",
     "lib/talia_dependencies.rb",
     "lib/talia_util.rb",
     "lib/talia_util/bar_progressor.rb",
     "lib/talia_util/configuration/config_file.rb",
     "lib/talia_util/configuration/database_config.rb",
     "lib/talia_util/configuration/mysql_database_setup.rb",
     "lib/talia_util/data_import.rb",
     "lib/talia_util/image_conversions.rb",
     "lib/talia_util/import_job_helper.rb",
     "lib/talia_util/io_helper.rb",
     "lib/talia_util/progressable.rb",
     "lib/talia_util/progressbar.rb",
     "lib/talia_util/rdf_update.rb",
     "lib/talia_util/some_sigla.xml",
     "lib/talia_util/test_helpers.rb",
     "lib/talia_util/util.rb",
     "lib/talia_util/yaml_import.rb",
     "lib/user.rb",
     "lib/version.rb"
  ]
  s.homepage = %q{http://trac.talia.discovery-project.eu/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.required_ruby_version = Gem::Requirement.new(">= 1.8.6")
  s.requirements = ["rdflib (Redland RDF) + Ruby bindings (for Redland store)"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{The core elements of the Talia Digital Library system}
  s.test_files = [
    "test/custom_template_test.rb",
     "test/test_helper.rb",
     "test/core_ext/string_test.rb",
     "test/talia_core/active_source_predicate_test.rb",
     "test/talia_core/active_source_rdf_test.rb",
     "test/talia_core/active_source_test.rb",
     "test/talia_core/generic_xml_test.rb",
     "test/talia_core/initializer_test.rb",
     "test/talia_core/ordered_source_test.rb",
     "test/talia_core/rdf_resource_test.rb",
     "test/talia_core/semantic_collection_item_test.rb",
     "test/talia_core/source_reader_test.rb",
     "test/talia_core/source_test.rb",
     "test/talia_core/source_transfer_object_test.rb",
     "test/talia_core/workflow_test.rb",
     "test/talia_core/data_types/data_loader_test.rb",
     "test/talia_core/data_types/data_record_test.rb",
     "test/talia_core/data_types/file_record_test.rb",
     "test/talia_core/data_types/iip_data_test.rb",
     "test/talia_core/data_types/image_data_test.rb",
     "test/talia_core/data_types/pdf_data_test.rb",
     "test/talia_core/data_types/xml_data_test.rb",
     "test/talia_core/workflow/publication_workflow_test.rb",
     "test/talia_core/workflow/user_class_for_workflow.rb",
     "test/talia_core/workflow/workflow_base_test.rb",
     "test/talia_util/import_job_helper_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 1.99.1"])
      s.add_runtime_dependency(%q<activesupport>, [">= 1.99.1"])
      s.add_runtime_dependency(%q<activerdf>, [">= 1.7.0"])
      s.add_runtime_dependency(%q<assit>, [">= 0.0.1"])
      s.add_runtime_dependency(%q<semantic_naming>, [">= 0.0.1"])
      s.add_runtime_dependency(%q<builder>, [">= 2.1.2"])
      s.add_runtime_dependency(%q<optiflag>, [">= 0.6.5"])
      s.add_runtime_dependency(%q<rake>, [">= 0.7.1"])
      s.add_runtime_dependency(%q<json>, [">= 1.1.0"])
    else
      s.add_dependency(%q<activerecord>, [">= 1.99.1"])
      s.add_dependency(%q<activesupport>, [">= 1.99.1"])
      s.add_dependency(%q<activerdf>, [">= 1.7.0"])
      s.add_dependency(%q<assit>, [">= 0.0.1"])
      s.add_dependency(%q<semantic_naming>, [">= 0.0.1"])
      s.add_dependency(%q<builder>, [">= 2.1.2"])
      s.add_dependency(%q<optiflag>, [">= 0.6.5"])
      s.add_dependency(%q<rake>, [">= 0.7.1"])
      s.add_dependency(%q<json>, [">= 1.1.0"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 1.99.1"])
    s.add_dependency(%q<activesupport>, [">= 1.99.1"])
    s.add_dependency(%q<activerdf>, [">= 1.7.0"])
    s.add_dependency(%q<assit>, [">= 0.0.1"])
    s.add_dependency(%q<semantic_naming>, [">= 0.0.1"])
    s.add_dependency(%q<builder>, [">= 2.1.2"])
    s.add_dependency(%q<optiflag>, [">= 0.6.5"])
    s.add_dependency(%q<rake>, [">= 0.7.1"])
    s.add_dependency(%q<json>, [">= 1.1.0"])
  end
end
