# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{talia_core}
  s.version = "0.7.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Danilo Giacomi", "Roberto Tofani", "Luca Guidi", "Michele Nucci", "Daniel Hahn"]
  s.date = %q{2010-11-24}
  s.default_executable = %q{talia}
  s.description = %q{This is the core plugin for building a digital library with Talia/Rails.}
  s.email = %q{ghub@limitedcreativity.org}
  s.executables = ["talia"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "VERSION.yml",
     "config/database.yml.example",
     "config/rdfstore.yml.example",
     "config/rdfstore.yml.rdflite_example",
     "config/rdfstore.yml.redland_example",
     "config/talia_core.yml.example",
     "generators/generator_helpers.rb",
     "generators/talia_admin/USAGE",
     "generators/talia_admin/talia_admin_generator.rb",
     "generators/talia_admin/templates/app/controllers/admin/admin_site_controller.rb",
     "generators/talia_admin/templates/app/controllers/admin/custom_templates_controller.rb",
     "generators/talia_admin/templates/app/controllers/admin/front_controller.rb",
     "generators/talia_admin/templates/app/controllers/admin/talia_collections_controller.rb",
     "generators/talia_admin/templates/app/controllers/admin/talia_sources_controller.rb",
     "generators/talia_admin/templates/app/controllers/admin/users_controller.rb",
     "generators/talia_admin/templates/app/controllers/users_controller.rb",
     "generators/talia_admin/templates/app/helpers/admin/front_helper.rb",
     "generators/talia_admin/templates/app/helpers/admin/talia_sources_helper.rb",
     "generators/talia_admin/templates/app/helpers/users_helper.rb",
     "generators/talia_admin/templates/app/models/fake_source.rb",
     "generators/talia_admin/templates/app/models/guest.rb",
     "generators/talia_admin/templates/app/models/talia_collection.rb",
     "generators/talia_admin/templates/app/models/talia_source.rb",
     "generators/talia_admin/templates/app/models/user.rb",
     "generators/talia_admin/templates/app/models/user_mailer.rb",
     "generators/talia_admin/templates/app/viewhints/talia_source_hints.rb",
     "generators/talia_admin/templates/app/views/admin/custom_templates/index.dryml",
     "generators/talia_admin/templates/app/views/admin/front/index.dryml",
     "generators/talia_admin/templates/app/views/admin/front/summary.dryml",
     "generators/talia_admin/templates/app/views/admin/talia_collections/index.dryml",
     "generators/talia_admin/templates/app/views/admin/talia_sources/index.dryml",
     "generators/talia_admin/templates/app/views/admin/talia_sources/show.dryml",
     "generators/talia_admin/templates/app/views/admin/users/index.dryml",
     "generators/talia_admin/templates/app/views/taglibs/admin_site.dryml",
     "generators/talia_admin/templates/app/views/taglibs/application.dryml",
     "generators/talia_admin/templates/app/views/taglibs/auto/admin/rapid/cards.dryml",
     "generators/talia_admin/templates/app/views/taglibs/auto/admin/rapid/forms.dryml",
     "generators/talia_admin/templates/app/views/taglibs/auto/admin/rapid/pages.dryml",
     "generators/talia_admin/templates/app/views/taglibs/auto/rapid/cards.dryml",
     "generators/talia_admin/templates/app/views/taglibs/auto/rapid/forms.dryml",
     "generators/talia_admin/templates/app/views/taglibs/auto/rapid/pages.dryml",
     "generators/talia_admin/templates/app/views/taglibs/front_site.dryml",
     "generators/talia_admin/templates/app/views/taglibs/themes/clean/clean.dryml",
     "generators/talia_admin/templates/app/views/user_mailer/forgot_password.erb",
     "generators/talia_admin/templates/config/hobo_initializer.rb",
     "generators/talia_admin/templates/migrations/create_users.rb",
     "generators/talia_admin/templates/public/hobothemes/clean/images/101-3B5F87-ACD3E6.png",
     "generators/talia_admin/templates/public/hobothemes/clean/images/30-3E547A-242E42.png",
     "generators/talia_admin/templates/public/hobothemes/clean/images/30-DBE1E5-FCFEF5.png",
     "generators/talia_admin/templates/public/hobothemes/clean/images/300-ACD3E6-fff.png",
     "generators/talia_admin/templates/public/hobothemes/clean/images/50-ACD3E6-fff.png",
     "generators/talia_admin/templates/public/hobothemes/clean/images/fieldbg.gif",
     "generators/talia_admin/templates/public/hobothemes/clean/images/pencil.png",
     "generators/talia_admin/templates/public/hobothemes/clean/images/small_close.png",
     "generators/talia_admin/templates/public/hobothemes/clean/images/spinner.gif",
     "generators/talia_admin/templates/public/hobothemes/clean/stylesheets/clean.css",
     "generators/talia_admin/templates/public/hobothemes/clean/stylesheets/rapid-ui.css",
     "generators/talia_admin/templates/public/javascripts/IE7.js",
     "generators/talia_admin/templates/public/javascripts/blank.gif",
     "generators/talia_admin/templates/public/javascripts/dryml-support.js",
     "generators/talia_admin/templates/public/javascripts/hobo-rapid.js",
     "generators/talia_admin/templates/public/javascripts/ie7-recalc.js",
     "generators/talia_admin/templates/public/javascripts/lowpro.js",
     "generators/talia_admin/templates/public/stylesheets/application.css",
     "generators/talia_admin/templates/public/stylesheets/hobo-rapid.css",
     "generators/talia_admin/templates/public/stylesheets/reset.css",
     "generators/talia_admin/templates/test/fixtures/users.yml",
     "generators/talia_admin/templates/test/functional/admin/front_controller_test.rb",
     "generators/talia_admin/templates/test/functional/users_controller_test.rb",
     "generators/talia_admin/templates/test/unit/user_test.rb",
     "generators/talia_base/USAGE",
     "generators/talia_base/talia_base_generator.rb",
     "generators/talia_base/templates/README",
     "generators/talia_base/templates/app/controllers/custom_templates_controller.rb",
     "generators/talia_base/templates/app/controllers/ontologies_controller.rb",
     "generators/talia_base/templates/app/controllers/source_data_controller.rb",
     "generators/talia_base/templates/app/controllers/sources_controller.rb",
     "generators/talia_base/templates/app/controllers/types_controller.rb",
     "generators/talia_base/templates/app/helpers/custom_templates_helper.rb",
     "generators/talia_base/templates/app/helpers/ontologies_helper.rb",
     "generators/talia_base/templates/app/helpers/source_data_helper.rb",
     "generators/talia_base/templates/app/helpers/sources_helper.rb",
     "generators/talia_base/templates/app/helpers/types_helper.rb",
     "generators/talia_base/templates/app/views/layouts/sources.html.erb",
     "generators/talia_base/templates/app/views/ontologies/index.builder",
     "generators/talia_base/templates/app/views/ontologies/show.builder",
     "generators/talia_base/templates/app/views/source_data/show.html.erb",
     "generators/talia_base/templates/app/views/sources/_data_list.html.erb",
     "generators/talia_base/templates/app/views/sources/_form.html.erb",
     "generators/talia_base/templates/app/views/sources/_property_item.html.erb",
     "generators/talia_base/templates/app/views/sources/_property_list.html.erb",
     "generators/talia_base/templates/app/views/sources/edit.html.erb",
     "generators/talia_base/templates/app/views/sources/index.html.erb",
     "generators/talia_base/templates/app/views/sources/new.html.erb",
     "generators/talia_base/templates/app/views/sources/semantic_templates/default/default.html.erb",
     "generators/talia_base/templates/app/views/sources/show.html.erb",
     "generators/talia_base/templates/app/views/types/index.html.erb",
     "generators/talia_base/templates/app/views/types/show.html.erb",
     "generators/talia_base/templates/config/routes.rb",
     "generators/talia_base/templates/config/talia_initializer.rb",
     "generators/talia_base/templates/config/warble.rb",
     "generators/talia_base/templates/migrations/constraint_migration.rb",
     "generators/talia_base/templates/migrations/create_active_sources.rb",
     "generators/talia_base/templates/migrations/create_custom_templates.rb",
     "generators/talia_base/templates/migrations/create_data_records.rb",
     "generators/talia_base/templates/migrations/create_progress_jobs.rb",
     "generators/talia_base/templates/migrations/create_semantic_properties.rb",
     "generators/talia_base/templates/migrations/create_semantic_relations.rb",
     "generators/talia_base/templates/migrations/create_workflows.rb",
     "generators/talia_base/templates/migrations/upgrade_relations.rb",
     "generators/talia_base/templates/ontologies/hyper_ontology.owl",
     "generators/talia_base/templates/ontologies/hyper_ontology.pprj",
     "generators/talia_base/templates/ontologies/hyper_ontology.repository",
     "generators/talia_base/templates/ontologies/scholar_0.1.owl",
     "generators/talia_base/templates/public/images/talia_core/building.png",
     "generators/talia_base/templates/public/images/talia_core/document-horizontal-text.png",
     "generators/talia_base/templates/public/images/talia_core/document.png",
     "generators/talia_base/templates/public/images/talia_core/gear.png",
     "generators/talia_base/templates/public/images/talia_core/group.png",
     "generators/talia_base/templates/public/images/talia_core/image.png",
     "generators/talia_base/templates/public/images/talia_core/imagebig.png",
     "generators/talia_base/templates/public/images/talia_core/letter.png",
     "generators/talia_base/templates/public/images/talia_core/map.png",
     "generators/talia_base/templates/public/images/talia_core/period.png",
     "generators/talia_base/templates/public/images/talia_core/person.png",
     "generators/talia_base/templates/public/images/talia_core/person_default.png",
     "generators/talia_base/templates/public/images/talia_core/place.png",
     "generators/talia_base/templates/public/images/talia_core/source.png",
     "generators/talia_base/templates/public/images/talia_core/television.png",
     "generators/talia_base/templates/public/images/talia_core/text.png",
     "generators/talia_base/templates/public/images/talia_core/type.png",
     "generators/talia_base/templates/public/images/talia_core/video.png",
     "generators/talia_base/templates/public/stylesheets/talia_core/images/arrow.png",
     "generators/talia_base/templates/public/stylesheets/talia_core/images/contents_top_left.gif",
     "generators/talia_base/templates/public/stylesheets/talia_core/images/header_bg.gif",
     "generators/talia_base/templates/public/stylesheets/talia_core/images/left_edge.gif",
     "generators/talia_base/templates/public/stylesheets/talia_core/images/line.png",
     "generators/talia_base/templates/public/stylesheets/talia_core/images/logo.gif",
     "generators/talia_base/templates/public/stylesheets/talia_core/main.css",
     "generators/talia_base/templates/script/configure_talia",
     "generators/talia_base/templates/script/prepare_images",
     "generators/talia_base/templates/talia.sh",
     "generators/talia_base/templates/tasks/talia_core.rk",
     "generators/talia_oai/USAGE",
     "generators/talia_oai/talia_oai_generator.rb",
     "generators/talia_oai/templates/oai_controller.rb",
     "generators/talia_oai/templates/oai_initializer.rb",
     "generators/talia_swicky/talia_swicky_generator.rb",
     "generators/talia_swicky/templates/app/controllers/swicky_notebooks_controller.rb",
     "generators/talia_swicky/templates/app/helpers/swicky_notebooks_helper.rb",
     "generators/talia_swicky/templates/app/views/swicky_notebooks/index.builder",
     "generators/talia_swicky/templates/app/views/swicky_notebooks/index.html.erb",
     "generators/talia_swicky/templates/app/views/swicky_notebooks/show.html.erb",
     "generators/talia_swicky/templates/test/fixtures/notebook.rdf",
     "generators/talia_swicky/templates/test/functional/swicky_notebooks_controller_test.rb",
     "lib/core_ext.rb",
     "lib/core_ext/boolean.rb",
     "lib/core_ext/jdbc_rake_monkeypatch.rb",
     "lib/core_ext/nil_class.rb",
     "lib/core_ext/object.rb",
     "lib/core_ext/platform.rb",
     "lib/core_ext/string.rb",
     "lib/custom_template.rb",
     "lib/loader_helper.rb",
     "lib/mysql.rb",
     "lib/progressbar.rb",
     "lib/swicky/api_result.rb",
     "lib/swicky/exhibit_json/item.rb",
     "lib/swicky/exhibit_json/item_collection.rb",
     "lib/swicky/fragment.rb",
     "lib/swicky/note.rb",
     "lib/swicky/notebook.rb",
     "lib/talia_core.rb",
     "lib/talia_core/active_source.rb",
     "lib/talia_core/active_source_parts/class_methods.rb",
     "lib/talia_core/active_source_parts/finders.rb",
     "lib/talia_core/active_source_parts/predicate_handler.rb",
     "lib/talia_core/active_source_parts/rdf/ntriples_reader.rb",
     "lib/talia_core/active_source_parts/rdf/rdf_reader.rb",
     "lib/talia_core/active_source_parts/rdf/rdfxml_reader.rb",
     "lib/talia_core/active_source_parts/rdf_handler.rb",
     "lib/talia_core/active_source_parts/sql_helper.rb",
     "lib/talia_core/active_source_parts/xml/generic_reader.rb",
     "lib/talia_core/active_source_parts/xml/generic_reader_add_statements.rb",
     "lib/talia_core/active_source_parts/xml/generic_reader_helpers.rb",
     "lib/talia_core/active_source_parts/xml/generic_reader_import_statements.rb",
     "lib/talia_core/active_source_parts/xml/rdf_builder.rb",
     "lib/talia_core/active_source_parts/xml/source_builder.rb",
     "lib/talia_core/active_source_parts/xml/source_reader.rb",
     "lib/talia_core/collection.rb",
     "lib/talia_core/data_types/data_loader.rb",
     "lib/talia_core/data_types/data_record.rb",
     "lib/talia_core/data_types/delayed_copier.rb",
     "lib/talia_core/data_types/file_record.rb",
     "lib/talia_core/data_types/file_store.rb",
     "lib/talia_core/data_types/iip_data.rb",
     "lib/talia_core/data_types/iip_loader.rb",
     "lib/talia_core/data_types/image_data.rb",
     "lib/talia_core/data_types/media_link.rb",
     "lib/talia_core/data_types/mime_mapping.rb",
     "lib/talia_core/data_types/path_helpers.rb",
     "lib/talia_core/data_types/pdf_data.rb",
     "lib/talia_core/data_types/simple_text.rb",
     "lib/talia_core/data_types/xml_data.rb",
     "lib/talia_core/dummy_handler.rb",
     "lib/talia_core/errors.rb",
     "lib/talia_core/initializer.rb",
     "lib/talia_core/oai/active_source_model.rb",
     "lib/talia_core/oai/active_source_oai_adapter.rb",
     "lib/talia_core/oai/active_source_oai_adapter/class_methods.rb",
     "lib/talia_core/property_string.rb",
     "lib/talia_core/rdf_import.rb",
     "lib/talia_core/rdf_resource.rb",
     "lib/talia_core/semantic_collection_wrapper.rb",
     "lib/talia_core/semantic_property.rb",
     "lib/talia_core/semantic_relation.rb",
     "lib/talia_core/source.rb",
     "lib/talia_core/source_fragment.rb",
     "lib/talia_core/source_transfer_object.rb",
     "lib/talia_core/source_types/agent.rb",
     "lib/talia_core/source_types/dc_resource.rb",
     "lib/talia_core/source_types/dummy_source.rb",
     "lib/talia_core/source_types/marcont_resource.rb",
     "lib/talia_core/source_types/skos_concept.rb",
     "lib/talia_core/workflow.rb",
     "lib/talia_core/workflow/base.rb",
     "lib/talia_core/workflow/publication_workflow.rb",
     "lib/talia_dependencies.rb",
     "lib/talia_util.rb",
     "lib/talia_util/bar_progressor.rb",
     "lib/talia_util/configuration/config_file.rb",
     "lib/talia_util/configuration/database_config.rb",
     "lib/talia_util/configuration/mysql_database_setup.rb",
     "lib/talia_util/image_conversions.rb",
     "lib/talia_util/import_job_helper.rb",
     "lib/talia_util/io_helper.rb",
     "lib/talia_util/progressable.rb",
     "lib/talia_util/rake_tasks.rb",
     "lib/talia_util/rdf_update.rb",
     "lib/talia_util/test_helpers.rb",
     "lib/talia_util/uri_helper.rb",
     "lib/talia_util/util.rb",
     "lib/talia_util/xml/base_builder.rb",
     "lib/talia_util/xml/rdf_builder.rb",
     "lib/tasks/talia_core_tasks.rake",
     "lib/version.rb"
  ]
  s.homepage = %q{http://trac.talia.discovery-project.eu/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.required_ruby_version = Gem::Requirement.new(">= 1.8.6")
  s.requirements = ["rdflib (Redland RDF) + Ruby bindings (for Redland store)"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{The core elements of the Talia Digital Library system}
  s.test_files = [
    "test/test_helper.rb",
     "test/custom_template_test.rb",
     "test/talia_util/import_job_helper_test.rb",
     "test/talia_util/io_helper_test.rb",
     "test/talia_util/rdf_builder_test.rb",
     "test/swicky/json_encoder_test.rb",
     "test/swicky/notebook_test.rb",
     "test/talia_core/source_transfer_object_test.rb",
     "test/talia_core/active_source_test.rb",
     "test/talia_core/source_reader_test.rb",
     "test/talia_core/rdfxml_reader_test.rb",
     "test/talia_core/active_source_rdf_test.rb",
     "test/talia_core/generic_xml_test.rb",
     "test/talia_core/property_string_test.rb",
     "test/talia_core/ntriples_reader_test.rb",
     "test/talia_core/active_source_finder_interface_test.rb",
     "test/talia_core/initializer_test.rb",
     "test/talia_core/rdf_resource_test.rb",
     "test/talia_core/source_test.rb",
     "test/talia_core/collection_test.rb",
     "test/talia_core/active_source_predicate_test.rb",
     "test/talia_core/workflow_test.rb",
     "test/talia_core/workflow/user_class_for_workflow.rb",
     "test/talia_core/workflow/workflow_base_test.rb",
     "test/talia_core/workflow/publication_workflow_test.rb",
     "test/talia_core/data_types/image_data_test.rb",
     "test/talia_core/data_types/iip_data_test.rb",
     "test/talia_core/data_types/file_record_test.rb",
     "test/talia_core/data_types/mime_mapping_test.rb",
     "test/talia_core/data_types/data_loader_test.rb",
     "test/talia_core/data_types/xml_data_test.rb",
     "test/talia_core/data_types/pdf_data_test.rb",
     "test/talia_core/data_types/data_record_test.rb",
     "test/core_ext/boolean_test.rb",
     "test/core_ext/nil_class_test.rb",
     "test/core_ext/string_test.rb",
     "test/core_ext/object_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, ["= 2.3.10"])
      s.add_runtime_dependency(%q<activesupport>, ["= 2.3.10"])
      s.add_runtime_dependency(%q<activerdf_net7>, [">= 1.7.0"])
      s.add_runtime_dependency(%q<assit>, [">= 0.1.2"])
      s.add_runtime_dependency(%q<semantic_naming>, [">= 2.2.0"])
      s.add_runtime_dependency(%q<bjj>, [">= 1.0.2"])
      s.add_runtime_dependency(%q<hpricot>, [">= 0.6.1"])
      s.add_runtime_dependency(%q<oai_talia>, [">= 0.0.15"])
      s.add_runtime_dependency(%q<builder>, [">= 2.1.2"])
      s.add_runtime_dependency(%q<optiflag>, [">= 0.6.5"])
      s.add_runtime_dependency(%q<rake>, [">= 0.7.1"])
      s.add_runtime_dependency(%q<guid>, [">= 0.1.1"])
      s.add_runtime_dependency(%q<rdf>, [">= 0.2.0.1"])
    else
      s.add_dependency(%q<activerecord>, ["= 2.3.10"])
      s.add_dependency(%q<activesupport>, ["= 2.3.10"])
      s.add_dependency(%q<activerdf_net7>, [">= 1.7.0"])
      s.add_dependency(%q<assit>, [">= 0.1.2"])
      s.add_dependency(%q<semantic_naming>, [">= 2.2.0"])
      s.add_dependency(%q<bjj>, [">= 1.0.2"])
      s.add_dependency(%q<hpricot>, [">= 0.6.1"])
      s.add_dependency(%q<oai_talia>, [">= 0.0.15"])
      s.add_dependency(%q<builder>, [">= 2.1.2"])
      s.add_dependency(%q<optiflag>, [">= 0.6.5"])
      s.add_dependency(%q<rake>, [">= 0.7.1"])
      s.add_dependency(%q<guid>, [">= 0.1.1"])
      s.add_dependency(%q<rdf>, [">= 0.2.0.1"])
    end
  else
    s.add_dependency(%q<activerecord>, ["= 2.3.10"])
    s.add_dependency(%q<activesupport>, ["= 2.3.10"])
    s.add_dependency(%q<activerdf_net7>, [">= 1.7.0"])
    s.add_dependency(%q<assit>, [">= 0.1.2"])
    s.add_dependency(%q<semantic_naming>, [">= 2.2.0"])
    s.add_dependency(%q<bjj>, [">= 1.0.2"])
    s.add_dependency(%q<hpricot>, [">= 0.6.1"])
    s.add_dependency(%q<oai_talia>, [">= 0.0.15"])
    s.add_dependency(%q<builder>, [">= 2.1.2"])
    s.add_dependency(%q<optiflag>, [">= 0.6.5"])
    s.add_dependency(%q<rake>, [">= 0.7.1"])
    s.add_dependency(%q<guid>, [">= 0.1.1"])
    s.add_dependency(%q<rdf>, [">= 0.2.0.1"])
  end
end

